### ISSUE TITLE
Flex menu can be opened in the App Store version of the app

### ISSUE THREAD

**Issue by ThomasK33** [khoren93/SwiftHub#11]
**Describe the bug**
The flex debug menu opens in the app store version of the app when swiping back with only one finger.

**To Reproduce**
1. Start the App Store version of the app.
2. Swipe from the left edge of the screen to the right edge / middle of the screen.

**Expected behavior**
The flex debug menu shall not appear in the app store build.

**Smartphone (please complete the following information):**
 - Device: iPhone Xs
 - OS: 12.2 (16E5201e)

**Comment by khoren93** [comment]
Hi @ThomasK33 

I specifically left the opportunity to open flex, because this project is primarily an educational app and only for developers.

In terms of security, I considered the fact that in almost any app from the App Store can be injected Flex using the [IPAPatch](https://github.com/Naituw/IPAPatch). (I played GTA San Andreas with injected Flex 😁)

Thanks for an issue.

**Comment by ThomasK33** [comment]
Oh, if that was intentional then I'm going to close the issue.
